### ISSUE TITLE
NPE when importing gradle projects

### ISSUE THREAD

**Issue by gayanper** [bvfalcon/kotlin-eclipse#3]
```
java.lang.NullPointerException: Platform.getBundle("org.…t(FileLocator::toFileURL) must not be null
	at org.jetbrains.kotlin.gradle.initialization.ModelInjector$Companion$modelLibPath$2.invoke(ModelInjector.kt:28)
	at org.jetbrains.kotlin.gradle.initialization.ModelInjector$Companion$modelLibPath$2.invoke(ModelInjector.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.gradle.initialization.ModelInjector$Companion.getModelLibPath(ModelInjector.kt)
	at org.jetbrains.kotlin.gradle.initialization.ModelInjector$Companion.access$getModelLibPath$p(ModelInjector.kt:15)
	at org.jetbrains.kotlin.gradle.initialization.ModelInjector.getExtraArguments(ModelInjector.kt:13)
	at org.eclipse.buildship.core.internal.invocation.InvocationCustomizerCollector.collectArguments(InvocationCustomizerCollector.java:40)
	at org.eclipse.buildship.core.internal.invocation.InvocationCustomizerCollector.getExtraArguments(InvocationCustomizerCollector.java:34)
	at org.eclipse.buildship.core.internal.configuration.GradleArguments.collectArguments(GradleArguments.java:135)
	at org.eclipse.buildship.core.internal.configuration.GradleArguments.applyTo(GradleArguments.java:110)
	at org.eclipse.buildship.core.internal.util.gradle.IdeAttachedProjectConnection.configureOperation(IdeAttachedProjectConnection.java:69)
	at org.eclipse.buildship.core.internal.util.gradle.IdeAttachedProjectConnection.model(IdeAttachedProjectConnection.java:59)
	at org.eclipse.buildship.core.internal.util.gradle.IdeAttachedProjectConnection.getModel(IdeAttachedProjectConnection.java:86)
	at org.eclipse.buildship.core.internal.workspace.DefaultModelProvider.queryModel(DefaultModelProvider.java:115)
	at org.eclipse.buildship.core.internal.workspace.DefaultModelProvider.lambda$null$0(DefaultModelProvider.java:50)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$GradleConnectionOperation.runInToolingApi(DefaultGradleBuild.java:329)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:58)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:39)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild.withConnection(DefaultGradleBuild.java:122)
	at org.eclipse.buildship.core.internal.workspace.DefaultModelProvider.lambda$fetchModel$1(DefaultModelProvider.java:49)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4878)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4873)
	at org.eclipse.buildship.core.internal.workspace.DefaultModelProvider.getFromCache(DefaultModelProvider.java:98)
	at org.eclipse.buildship.core.internal.workspace.DefaultModelProvider.executeOperation(DefaultModelProvider.java:90)
	at org.eclipse.buildship.core.internal.workspace.DefaultModelProvider.fetchModel(DefaultModelProvider.java:48)
	at org.eclipse.buildship.ui.internal.wizard.project.ProjectPreviewWizardPage.fetchBuildEnvironment(ProjectPreviewWizardPage.java:451)
	at org.eclipse.buildship.ui.internal.wizard.project.ProjectPreviewWizardPage.access$600(ProjectPreviewWizardPage.java:78)
	at org.eclipse.buildship.ui.internal.wizard.project.ProjectPreviewWizardPage$UpdatePreviewOperation.runInToolingApi(ProjectPreviewWizardPage.java:476)
	at org.eclipse.buildship.core.internal.operation.ToolingApiOperations$1.runInToolingApi(ToolingApiOperations.java:60)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:58)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:39)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:33)
	at org.eclipse.buildship.ui.internal.wizard.project.ProjectPreviewWizardPage$4.run(ProjectPreviewWizardPage.java:311)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by bvfalcon** [comment]
Please attach project with this error.
I try import [this gradle](https://github.com/Kotlin/kotlin-examples/tree/master/gradle/hello-world) project and all was Ok: import, gradle tasks (clean, build, jar, test). Error was not acquired with hello-world.

**Comment by gayanper** [comment]
The project is a proprietary project. But i will try to debug it and share my findings, may be a PR as well if i figure out how to fix it.
